// Copyright (c) 2026 The Lattice contributors
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

// Code generated by node/cmd/gengenesis. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./node/cmd/gengenesis > node/chaincfg/genesis.go
//
// TestGenesisIsReproducible in genesis_test.go re-derives every hash below and
// fails if a literal here has drifted from the block it claims to describe.

package chaincfg

import (
	"time"

	"github.com/codeminute-the-dev/lattice/node/chaincfg/chainhash"
	"github.com/codeminute-the-dev/lattice/node/wire"
)

// genesisCoinbaseTx is the coinbase transaction for the genesis blocks of
// every Lattice network.
//
// Its single output pays a value of 0 to a bare OP_RETURN, which is provably
// unspendable. No address, no allocation, no founder reward: the chain begins
// with zero coins in existence and every LATT that will ever exist is mined
// after this block.
var genesisCoinbaseTx = wire.MsgTx{
	Version: 1,
	TxIn: []*wire.TxIn{
		{
			PreviousOutPoint: wire.OutPoint{
				Hash:  chainhash.Hash{},
				Index: 0xffffffff,
			},
			// Lattice: useful work, fair launch. No premine, no founder allocation. Reward 2 LATT, cumulative h/(h+39420000), reset every 3153600 blocks, WTEMA 40s 24h. Bitcoin block #963094 is 00000000000000000001948df55d30651e4201e27df7cd41d8f1d1e81f2679b1.
			SignatureScript: []byte{
				0x04, 0xff, 0xff, 0x00, 0x1d, 0x01, 0x04, 0x4c,
				0xf5, 0x4c, 0x61, 0x74, 0x74, 0x69, 0x63, 0x65,
				0x3a, 0x20, 0x75, 0x73, 0x65, 0x66, 0x75, 0x6c,
				0x20, 0x77, 0x6f, 0x72, 0x6b, 0x2c, 0x20, 0x66,
				0x61, 0x69, 0x72, 0x20, 0x6c, 0x61, 0x75, 0x6e,
				0x63, 0x68, 0x2e, 0x20, 0x4e, 0x6f, 0x20, 0x70,
				0x72, 0x65, 0x6d, 0x69, 0x6e, 0x65, 0x2c, 0x20,
				0x6e, 0x6f, 0x20, 0x66, 0x6f, 0x75, 0x6e, 0x64,
				0x65, 0x72, 0x20, 0x61, 0x6c, 0x6c, 0x6f, 0x63,
				0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x20, 0x52,
				0x65, 0x77, 0x61, 0x72, 0x64, 0x20, 0x32, 0x20,
				0x4c, 0x41, 0x54, 0x54, 0x2c, 0x20, 0x63, 0x75,
				0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65,
				0x20, 0x68, 0x2f, 0x28, 0x68, 0x2b, 0x33, 0x39,
				0x34, 0x32, 0x30, 0x30, 0x30, 0x30, 0x29, 0x2c,
				0x20, 0x72, 0x65, 0x73, 0x65, 0x74, 0x20, 0x65,
				0x76, 0x65, 0x72, 0x79, 0x20, 0x33, 0x31, 0x35,
				0x33, 0x36, 0x30, 0x30, 0x20, 0x62, 0x6c, 0x6f,
				0x63, 0x6b, 0x73, 0x2c, 0x20, 0x57, 0x54, 0x45,
				0x4d, 0x41, 0x20, 0x34, 0x30, 0x73, 0x20, 0x32,
				0x34, 0x68, 0x2e, 0x20, 0x42, 0x69, 0x74, 0x63,
				0x6f, 0x69, 0x6e, 0x20, 0x62, 0x6c, 0x6f, 0x63,
				0x6b, 0x20, 0x23, 0x39, 0x36, 0x33, 0x30, 0x39,
				0x34, 0x20, 0x69, 0x73, 0x20, 0x30, 0x30, 0x30,
				0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30,
				0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30,
				0x31, 0x39, 0x34, 0x38, 0x64, 0x66, 0x35, 0x35,
				0x64, 0x33, 0x30, 0x36, 0x35, 0x31, 0x65, 0x34,
				0x32, 0x30, 0x31, 0x65, 0x32, 0x37, 0x64, 0x66,
				0x37, 0x63, 0x64, 0x34, 0x31, 0x64, 0x38, 0x66,
				0x31, 0x64, 0x31, 0x65, 0x38, 0x31, 0x66, 0x32,
				0x36, 0x37, 0x39, 0x62, 0x31, 0x2e,
			},
			Sequence: 0xffffffff,
		},
	},
	TxOut: []*wire.TxOut{
		{
			Value: 0x0,
			PkScript: []byte{
				0x6a, /* OP_RETURN — unspendable */
			},
		},
	},
	LockTime: 0,
}

// genesisMerkleRoot is the hash of genesisCoinbaseTx, shared by every
// network because they all use the same fair-launch coinbase.
var genesisMerkleRoot = chainhash.Hash([chainhash.HashSize]byte{
	0xb8, 0xdf, 0xf9, 0x7a, 0xb8, 0xdb, 0x84, 0x40,
	0x6f, 0xb7, 0x10, 0xe6, 0x87, 0xd3, 0xd1, 0x65,
	0x62, 0xc2, 0x87, 0xc9, 0x3d, 0x5a, 0x42, 0x2b,
	0x6c, 0x1f, 0x36, 0x2d, 0xe0, 0xf0, 0x45, 0x0e,
})

// genesisHash is the hash of the first block in the block chain for the
// main network (genesis block).
var genesisHash = chainhash.Hash([chainhash.HashSize]byte{
	0x9f, 0x81, 0xa9, 0xcf, 0x53, 0x3c, 0x3e, 0x74,
	0xcd, 0xc9, 0x2c, 0x47, 0x3a, 0xec, 0x61, 0xae,
	0x74, 0xb8, 0xa6, 0xca, 0xf8, 0x7d, 0xa3, 0x2d,
	0xa4, 0xc5, 0x2e, 0xfc, 0xa8, 0x00, 0x26, 0x01,
})

// genesisBlock defines the genesis block of the block chain which serves
// as the public transaction ledger for the main network.
var genesisBlock = wire.MsgBlock{
	MsgHeader: wire.MsgHeader{
		MsgCertificate: wire.MsgCertificate{
			Certificate: &wire.CertificateV1{
				Hash:      genesisHash,
				ProofData: []byte{0xde, 0xad, 0xbe, 0xef}, // Vanity proof for genesis block
			},
		},
		BlockHeader: wire.BlockHeader{
			Version:    1,
			PrevBlock:  chainhash.Hash{},
			MerkleRoot: genesisMerkleRoot,
			Timestamp:  time.Unix(1786518000, 0), // 2026-08-12 07:00:00 UTC
			Bits:       0x1e010000,
		},
	},
	Transactions: []*wire.MsgTx{&genesisCoinbaseTx},
}

// regTestGenesisHash is the hash of the first block in the block chain for the
// regression test network (genesis block).
var regTestGenesisHash = chainhash.Hash([chainhash.HashSize]byte{
	0x3a, 0x2d, 0x22, 0xd5, 0x1d, 0x25, 0xec, 0x17,
	0xe1, 0x2e, 0x26, 0xd3, 0x29, 0xf0, 0xfa, 0xf4,
	0x60, 0xb8, 0x08, 0xd6, 0xd4, 0x9c, 0x78, 0x85,
	0x73, 0x7c, 0x82, 0x94, 0x5c, 0xf2, 0xba, 0x29,
})

// regTestGenesisMerkleRoot is the merkle root of the regression test network genesis
// block. Every network shares the same coinbase, so it matches mainnet's.
var regTestGenesisMerkleRoot = genesisMerkleRoot

// regTestGenesisBlock defines the genesis block of the block chain which serves
// as the public transaction ledger for the regression test network.
var regTestGenesisBlock = wire.MsgBlock{
	MsgHeader: wire.MsgHeader{
		MsgCertificate: wire.MsgCertificate{
			Certificate: &wire.CertificateV1{
				Hash:      regTestGenesisHash,
				ProofData: []byte{0xde, 0xad, 0xbe, 0xef}, // Vanity proof for genesis block
			},
		},
		BlockHeader: wire.BlockHeader{
			Version:    1,
			PrevBlock:  chainhash.Hash{},
			MerkleRoot: regTestGenesisMerkleRoot,
			Timestamp:  time.Unix(1786258800, 0), // 2026-08-09 07:00:00 UTC
			Bits:       0x1e010000,
		},
	},
	Transactions: []*wire.MsgTx{&genesisCoinbaseTx},
}

// testNetGenesisHash is the hash of the first block in the block chain for the
// test network (genesis block).
var testNetGenesisHash = chainhash.Hash([chainhash.HashSize]byte{
	0xd4, 0x08, 0x73, 0xf3, 0x42, 0x97, 0x89, 0x07,
	0xdd, 0xe5, 0x1c, 0x82, 0xe8, 0xf6, 0x3a, 0xdf,
	0xbe, 0x93, 0x68, 0x5e, 0x58, 0x52, 0x17, 0x31,
	0x4b, 0x1e, 0xb5, 0x70, 0x88, 0x4d, 0x5d, 0xa8,
})

// testNetGenesisMerkleRoot is the merkle root of the test network genesis
// block. Every network shares the same coinbase, so it matches mainnet's.
var testNetGenesisMerkleRoot = genesisMerkleRoot

// testNetGenesisBlock defines the genesis block of the block chain which serves
// as the public transaction ledger for the test network.
var testNetGenesisBlock = wire.MsgBlock{
	MsgHeader: wire.MsgHeader{
		MsgCertificate: wire.MsgCertificate{
			Certificate: &wire.CertificateV1{
				Hash:      testNetGenesisHash,
				ProofData: []byte{0xde, 0xad, 0xbe, 0xef}, // Vanity proof for genesis block
			},
		},
		BlockHeader: wire.BlockHeader{
			Version:    1,
			PrevBlock:  chainhash.Hash{},
			MerkleRoot: testNetGenesisMerkleRoot,
			Timestamp:  time.Unix(1786431600, 0), // 2026-08-11 07:00:00 UTC
			Bits:       0x1e010000,
		},
	},
	Transactions: []*wire.MsgTx{&genesisCoinbaseTx},
}

// testNet2GenesisHash is the hash of the first block in the block chain for the
// test2 network (genesis block).
var testNet2GenesisHash = chainhash.Hash([chainhash.HashSize]byte{
	0x5c, 0x18, 0x1a, 0x9b, 0xe3, 0x0f, 0x15, 0xef,
	0x14, 0x80, 0x8d, 0x68, 0x0b, 0x1a, 0x57, 0x74,
	0x52, 0x59, 0x07, 0x8b, 0x15, 0x78, 0x28, 0x37,
	0x74, 0xab, 0xea, 0xb9, 0xe1, 0xa6, 0x73, 0xd7,
})

// testNet2GenesisMerkleRoot is the merkle root of the test2 network genesis
// block. Every network shares the same coinbase, so it matches mainnet's.
var testNet2GenesisMerkleRoot = genesisMerkleRoot

// testNet2GenesisBlock defines the genesis block of the block chain which serves
// as the public transaction ledger for the test2 network.
var testNet2GenesisBlock = wire.MsgBlock{
	MsgHeader: wire.MsgHeader{
		MsgCertificate: wire.MsgCertificate{
			Certificate: &wire.CertificateV1{
				Hash:      testNet2GenesisHash,
				ProofData: []byte{0xde, 0xad, 0xbe, 0xef}, // Vanity proof for genesis block
			},
		},
		BlockHeader: wire.BlockHeader{
			Version:    1,
			PrevBlock:  chainhash.Hash{},
			MerkleRoot: testNet2GenesisMerkleRoot,
			Timestamp:  time.Unix(1786345200, 0), // 2026-08-10 07:00:00 UTC
			Bits:       0x1e010000,
		},
	},
	Transactions: []*wire.MsgTx{&genesisCoinbaseTx},
}

// simNetGenesisHash is the hash of the first block in the block chain for the
// simulation test network (genesis block).
var simNetGenesisHash = chainhash.Hash([chainhash.HashSize]byte{
	0x34, 0xb1, 0x81, 0xc6, 0x15, 0x4f, 0xf5, 0x67,
	0x8b, 0x6b, 0xb3, 0xaa, 0xdf, 0x2b, 0x2c, 0x1b,
	0x26, 0x06, 0x14, 0x18, 0x5f, 0x5e, 0xb4, 0xfd,
	0xe6, 0x97, 0x79, 0xd1, 0x47, 0x10, 0xf9, 0xd5,
})

// simNetGenesisMerkleRoot is the merkle root of the simulation test network genesis
// block. Every network shares the same coinbase, so it matches mainnet's.
var simNetGenesisMerkleRoot = genesisMerkleRoot

// simNetGenesisBlock defines the genesis block of the block chain which serves
// as the public transaction ledger for the simulation test network.
var simNetGenesisBlock = wire.MsgBlock{
	MsgHeader: wire.MsgHeader{
		MsgCertificate: wire.MsgCertificate{
			Certificate: &wire.CertificateV1{
				Hash:      simNetGenesisHash,
				ProofData: []byte{0xde, 0xad, 0xbe, 0xef}, // Vanity proof for genesis block
			},
		},
		BlockHeader: wire.BlockHeader{
			Version:    1,
			PrevBlock:  chainhash.Hash{},
			MerkleRoot: simNetGenesisMerkleRoot,
			Timestamp:  time.Unix(1786172400, 0), // 2026-08-08 07:00:00 UTC
			Bits:       0x207fffff,
		},
	},
	Transactions: []*wire.MsgTx{&genesisCoinbaseTx},
}

// sigNetGenesisHash is the hash of the first block in the block chain for the
// signet test network (genesis block).
var sigNetGenesisHash = chainhash.Hash([chainhash.HashSize]byte{
	0xe6, 0xed, 0xf5, 0xd9, 0xe3, 0xd9, 0xdc, 0xb2,
	0x45, 0x48, 0xf7, 0xbd, 0x2a, 0x6c, 0xfe, 0x37,
	0x94, 0x1e, 0x19, 0xdb, 0x67, 0x27, 0x2b, 0x6e,
	0x82, 0x26, 0x65, 0x36, 0x15, 0x5f, 0x82, 0x95,
})

// sigNetGenesisMerkleRoot is the merkle root of the signet test network genesis
// block. Every network shares the same coinbase, so it matches mainnet's.
var sigNetGenesisMerkleRoot = genesisMerkleRoot

// sigNetGenesisBlock defines the genesis block of the block chain which serves
// as the public transaction ledger for the signet test network.
var sigNetGenesisBlock = wire.MsgBlock{
	MsgHeader: wire.MsgHeader{
		MsgCertificate: wire.MsgCertificate{
			Certificate: &wire.CertificateV1{
				Hash:      sigNetGenesisHash,
				ProofData: []byte{0xde, 0xad, 0xbe, 0xef}, // Vanity proof for genesis block
			},
		},
		BlockHeader: wire.BlockHeader{
			Version:    1,
			PrevBlock:  chainhash.Hash{},
			MerkleRoot: sigNetGenesisMerkleRoot,
			Timestamp:  time.Unix(1786086000, 0), // 2026-08-07 07:00:00 UTC
			Bits:       0x1d0fffff,
		},
	},
	Transactions: []*wire.MsgTx{&genesisCoinbaseTx},
}
