// Command gengenesis regenerates node/chaincfg/genesis.go.
//
// It exists so Lattice's genesis blocks are reproducible: anyone can run
//
//	go run ./node/cmd/gengenesis > node/chaincfg/genesis.go
//
// and confirm byte-for-byte that the committed genesis is the one this source
// describes. That is what makes the no-premine claim checkable rather than
// something taken on trust — the coinbase pays 0 to an unspendable OP_RETURN,
// and you can verify it yourself instead of believing a README.
package main

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/codeminute-the-dev/lattice/node/chaincfg/chainhash"
	"github.com/codeminute-the-dev/lattice/node/wire"
)

// The genesis coinbase message pins the launch parameters into the chain's
// first block and anchors it to a Bitcoin block that did not exist beforehand,
// which proves the genesis was not quietly mined ahead of its stated date.
const msg = "Lattice: useful work, fair launch. No premine, no founder allocation. " +
	"Reward 2 LATT, cumulative h/(h+39420000), reset every 3153600 blocks, WTEMA 40s 24h. " +
	"Bitcoin block #963094 is 00000000000000000001948df55d30651e4201e27df7cd41d8f1d1e81f2679b1."

func sigScript() []byte {
	s := []byte{0x04, 0xff, 0xff, 0x00, 0x1d, 0x01, 0x04}
	b := []byte(msg)
	if len(b) > 255 {
		panic("genesis message too long for OP_PUSHDATA1")
	}
	s = append(s, 0x4c, byte(len(b)))
	return append(s, b...)
}

func coinbase() *wire.MsgTx {
	return &wire.MsgTx{
		Version: 1,
		TxIn: []*wire.TxIn{{
			PreviousOutPoint: wire.OutPoint{Hash: chainhash.Hash{}, Index: 0xffffffff},
			SignatureScript:  sigScript(),
			Sequence:         0xffffffff,
		}},
		TxOut:    []*wire.TxOut{{Value: 0, PkScript: []byte{0x6a}}},
		LockTime: 0,
	}
}

func bytesLit(b []byte, indent string) string {
	var sb strings.Builder
	for i, x := range b {
		if i%8 == 0 {
			sb.WriteString("\n" + indent)
		}
		fmt.Fprintf(&sb, "0x%02x, ", x)
	}
	sb.WriteString("\n")
	return sb.String()
}

func hashLit(name, doc string, h chainhash.Hash) string {
	var sb strings.Builder
	sb.WriteString(doc)
	fmt.Fprintf(&sb, "var %s = chainhash.Hash([chainhash.HashSize]byte{", name)
	sb.WriteString(bytesLit(h[:], "\t"))
	sb.WriteString("})\n\n")
	return sb.String()
}

type net struct {
	label, hashVar, merkleVar, blockVar string
	ts                                  int64
	bits                                uint32
}

func main() {
	cb := coinbase()
	merkle := cb.TxHash()

	nets := []net{
		{"main", "genesisHash", "genesisMerkleRoot", "genesisBlock", 1786518000, 0x1b00ffff},
		{"regression test", "regTestGenesisHash", "regTestGenesisMerkleRoot", "regTestGenesisBlock", 1786258800, 0x1e010000},
		{"test", "testNetGenesisHash", "testNetGenesisMerkleRoot", "testNetGenesisBlock", 1786431600, 0x1d00ffff},
		{"test2", "testNet2GenesisHash", "testNet2GenesisMerkleRoot", "testNet2GenesisBlock", 1786345200, 0x1d00ffff},
		{"simulation test", "simNetGenesisHash", "simNetGenesisMerkleRoot", "simNetGenesisBlock", 1786172400, 0x207fffff},
		{"signet test", "sigNetGenesisHash", "sigNetGenesisMerkleRoot", "sigNetGenesisBlock", 1786086000, 0x1d0fffff},
	}

	var out strings.Builder
	out.WriteString(`// Copyright (c) 2026 The Lattice contributors
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

// Code generated by node/cmd/gengenesis. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./node/cmd/gengenesis > node/chaincfg/genesis.go
//
// TestGenesisIsReproducible in genesis_test.go re-derives every hash below and
// fails if a literal here has drifted from the block it claims to describe.

package chaincfg

import (
	"time"

	"github.com/codeminute-the-dev/lattice/node/chaincfg/chainhash"
	"github.com/codeminute-the-dev/lattice/node/wire"
)

// genesisCoinbaseTx is the coinbase transaction for the genesis blocks of
// every Lattice network.
//
// Its single output pays a value of 0 to a bare OP_RETURN, which is provably
// unspendable. No address, no allocation, no founder reward: the chain begins
// with zero coins in existence and every LATT that will ever exist is mined
// after this block.
var genesisCoinbaseTx = wire.MsgTx{
	Version: 1,
	TxIn: []*wire.TxIn{
		{
			PreviousOutPoint: wire.OutPoint{
				Hash:  chainhash.Hash{},
				Index: 0xffffffff,
			},
			// ` + msg + `
			SignatureScript: []byte{`)
	out.WriteString(bytesLit(sigScript(), "\t\t\t\t"))
	out.WriteString(`			},
			Sequence: 0xffffffff,
		},
	},
	TxOut: []*wire.TxOut{
		{
			Value: 0x0,
			PkScript: []byte{
				0x6a, /* OP_RETURN — unspendable */
			},
		},
	},
	LockTime: 0,
}

`)

	out.WriteString(hashLit("genesisMerkleRoot",
		"// genesisMerkleRoot is the hash of genesisCoinbaseTx, shared by every\n"+
			"// network because they all use the same fair-launch coinbase.\n", merkle))

	for i, n := range nets {
		hdr := wire.BlockHeader{
			Version:    1,
			PrevBlock:  chainhash.Hash{},
			MerkleRoot: merkle,
			Timestamp:  time.Unix(n.ts, 0),
			Bits:       n.bits,
		}
		h := hdr.BlockHash()

		out.WriteString(hashLit(n.hashVar,
			fmt.Sprintf("// %s is the hash of the first block in the block chain for the\n// %s network (genesis block).\n", n.hashVar, n.label), h))

		if i > 0 {
			fmt.Fprintf(&out, "// %s is the merkle root of the %s network genesis\n// block. Every network shares the same coinbase, so it matches mainnet's.\nvar %s = genesisMerkleRoot\n\n",
				n.merkleVar, n.label, n.merkleVar)
		}

		fmt.Fprintf(&out, `// %s defines the genesis block of the block chain which serves
// as the public transaction ledger for the %s network.
var %s = wire.MsgBlock{
	MsgHeader: wire.MsgHeader{
		MsgCertificate: wire.MsgCertificate{
			Certificate: &wire.CertificateV1{
				Hash:      %s,
				ProofData: []byte{0xde, 0xad, 0xbe, 0xef}, // Vanity proof for genesis block
			},
		},
		BlockHeader: wire.BlockHeader{
			Version:    1,
			PrevBlock:  chainhash.Hash{},
			MerkleRoot: %s,
			Timestamp:  time.Unix(%d, 0), // %s
			Bits:       %#08x,
		},
	},
	Transactions: []*wire.MsgTx{&genesisCoinbaseTx},
}

`, n.blockVar, n.label, n.blockVar, n.hashVar, n.merkleVar, n.ts,
			time.Unix(n.ts, 0).UTC().Format("2006-01-02 15:04:05 MST"), n.bits)
	}

	fmt.Fprint(os.Stdout, out.String())
}
